name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: |
          network=host
        buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host


    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Backend
      run: |
        docker build -t malavikaselvan899/backend:latest ./backend
        docker push malavikaselvan899/backend:latest

    - name: Build and Push Frontend
      run: |
        docker build -t malavikaselvan899/frontend:latest ./frontend
        docker push malavikaselvan899/frontend:latest

    - name: Deploy to Minikube
      run: |
        minikube start
        kubectl apply -f manifests/
