name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install frontend dependencies and run tests
      working-directory: frontend
      run: |
        npm install
        npm run test:coverage

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver: docker
          
    # - name: Login to DockerHub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Backend
      run: |
        cd backend
        docker build -t malavikaselvan899/backend:latest .
        docker push malavikaselvan899/backend:latest

    - name: Build and Push Frontend
      run: |
        cd frontend
        docker build -t malavikaselvan899/frontend:latest .
        docker push malavikaselvan899/frontend:latest

    - name: Deploy to Minikube
      run: |
        minikube start --driver=docker
        kubectl apply -f manifests/
